### ISSUE TITLE
400 Error when running action

### ISSUE THREAD

**Issue by frankrooneyjci** [mikesprague/teams-incoming-webhook-action#103]
Hi,

Thanks for releasing this github action.

I am attempting to use it in my project and I get a 400 error every time it runs.

Error: AxiosError: Request failed with status code 400

I feel like either my webhook is not setup correctly or something else?
I setup the WebHook as a "Connection" on a MS Teams Channel via the GitHub Enterprise app.

Thanks!

**Comment by frankrooneyjci** [comment]
I probably spoke too soon, 😓 It seems there are 2 ways to create a webhook, I just found the second method so I will try that when I can and revert.

**Comment by mikesprague** [comment]
Hello,

I have never used this in conjunction with GH Enterprise app in Teams and would have to point you to their documentation for any issues interfacing with that.

This particular action is expecting an MS Teams "Incoming Webhook" created from a channel's "Connectors" options.

I would try creating one of those and see if you have better luck.

It's possible that a feature to support the GH app webhooks could be added in the future but at this time the Incoming Webhook is what you need.

**Comment by frankrooneyjci** [comment]
@mikesprague It's a bad habit I have sometimes, I speak too soon! Thanks for the quick response!

**Comment by mikesprague** [comment]
@frankrooneyjci All good... def been there and done that. Hope that info gets you moving. Here's a link to the specific docs as well: <https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=dotnet>

I'm going to close this but feel free to reopen or create a new issue if you have further problems.

**Comment by frankrooneyjci** [comment]
Thats fine with me!
