### ISSUE TITLE
Unable to use action on non-Github repositories

### ISSUE THREAD

**Issue by hmhackmaster** [mikesprague/teams-incoming-webhook-action#236]
I have attempted to use this action on a self-hosted install of Gitea (using the act runner). 

Unfortunately, it looks like this action has several hardcoded references to Github, so it won't work at all if the repo that the action runs from is not hosted on Github.com
 
I am assuming other actions take advantage of the existing environmental variables (like `GITHUB_API_URL`) to detect the environment's git server (Github, Github enterprise, or something alternative like self-hosted Gitea).
It also looks like `@octokit/request` defaults to Github's API if the `baseUrl` parameter isn't specified.

Is use in non-Github.com environments a feature you are willing to include in this action?

**Comment by mikesprague** [comment]
Thanks for reaching out, and for the question.

Unfortunately, as I am not a user of Gitea (and therefore have no testing environments), I don't think it's very practical for me to _officially_ support their service with this Action. 

However, there was only one hardcoded URL and I was using the default config for `@octokit/request` - updating those to be dynamic is easy enough. 

Note that there's still no guarantee this will work for you in Gitea.

I will release those changes shortly.

**Comment by andre68723** [comment]
Hi Michael,  @mikesprague 

just wanting to give kudos to you for this excellent action. 

I'm myself using GHES and tested various ones last week, yours is the only one which actually works as expected.
Everything else had issues like not maintained, wrong node version, no support for variables in title/text, not supporting GHES a.s.o. 

Happy I found that one, MMD!

Thanks, Andre
