### ISSUE TITLE
Prop login?

### ISSUE THREAD

**Issue by ekandreas** [mikesprague/teams-incoming-webhook-action#68]
Run mikesprague/teams-incoming-webhook-action@v1
  with:
    github-token: ***
    webhook-url: ***
    color: success
    title: NNN
    message: NNN
    deploy-card: true
    timezone: Europe/Stockholm
Error: Cannot read properties of null (reading 'login')

**Comment by mikesprague** [comment]
I'll need some more information if you want help with this...

How did you invoke the action? 

If you manually ran it, there would be no commit author and it would be expected to fail. 

If you implemented in a repo, pushed a commit to the repo to cause the workflow to run, and then it still gave that error, then I'll need the logs from that run (versus just the error message).

Worth noting, with `deploy-card: true` you will need to initiate it with a commit. If you simply want to test sending a message, use `deploy-card: false` and it won't try to build the data from a git commit.

**Comment by mikesprague** [comment]
I'm going to close this for now since there's been no follow-up. Please feel free to re-open with additional details and full logs if you'd still like help. Thanks!

**Comment by mikesprague** [comment]
Seems to be same as #75 which has also provided enough detail for me to address

**Comment by mikesprague** [comment]
This should be fixed by the latest release via commit b76c30a

**Comment by ekandreas** [comment]
Thanks!
